version: '3.8'

services:
  portfolio-api:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server/data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3001
    restart: unless-stopped

  portfolio-frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    depends_on:
      - portfolio-api
    restart: unless-stopped
